// Generated by iod_generate_symbols.
#include <iod/symbol.hh>
#ifndef IOD_SYMBOL_1
#define IOD_SYMBOL_1
    iod_define_number_symbol(1)
#endif

#ifndef IOD_SYMBOL_approximation
#define IOD_SYMBOL_approximation
    iod_define_symbol(approximation)
#endif

#ifndef IOD_SYMBOL_block_size
#define IOD_SYMBOL_block_size
    iod_define_symbol(block_size)
#endif

#ifndef IOD_SYMBOL_blockwise
#define IOD_SYMBOL_blockwise
    iod_define_symbol(blockwise)
#endif

#ifndef IOD_SYMBOL_blockwise_rank
#define IOD_SYMBOL_blockwise_rank
    iod_define_symbol(blockwise_rank)
#endif

#ifndef IOD_SYMBOL_border
#define IOD_SYMBOL_border
    iod_define_symbol(border)
#endif

#ifndef IOD_SYMBOL_bottom_to_top
#define IOD_SYMBOL_bottom_to_top
    iod_define_symbol(bottom_to_top)
#endif

#ifndef IOD_SYMBOL_bruteforce
#define IOD_SYMBOL_bruteforce
    iod_define_symbol(bruteforce)
#endif

#ifndef IOD_SYMBOL_cell_width
#define IOD_SYMBOL_cell_width
    iod_define_symbol(cell_width)
#endif

#ifndef IOD_SYMBOL_delta
#define IOD_SYMBOL_delta
    iod_define_symbol(delta)
#endif

#ifndef IOD_SYMBOL_descriptor
#define IOD_SYMBOL_descriptor
    iod_define_symbol(descriptor)
#endif

#ifndef IOD_SYMBOL_detector_period
#define IOD_SYMBOL_detector_period
    iod_define_symbol(detector_period)
#endif

#ifndef IOD_SYMBOL_detector_th
#define IOD_SYMBOL_detector_th
    iod_define_symbol(detector_th)
#endif

#ifndef IOD_SYMBOL_distance
#define IOD_SYMBOL_distance
    iod_define_symbol(distance)
#endif

#ifndef IOD_SYMBOL_epipolar_filter
#define IOD_SYMBOL_epipolar_filter
    iod_define_symbol(epipolar_filter)
#endif

#ifndef IOD_SYMBOL_epipolar_flow
#define IOD_SYMBOL_epipolar_flow
    iod_define_symbol(epipolar_flow)
#endif

#ifndef IOD_SYMBOL_flann
#define IOD_SYMBOL_flann
    iod_define_symbol(flann)
#endif

#ifndef IOD_SYMBOL_flow
#define IOD_SYMBOL_flow
    iod_define_symbol(flow)
#endif

#ifndef IOD_SYMBOL_fundamental_matrix
#define IOD_SYMBOL_fundamental_matrix
    iod_define_symbol(fundamental_matrix)
#endif

#ifndef IOD_SYMBOL_idx
#define IOD_SYMBOL_idx
    iod_define_symbol(idx)
#endif

#ifndef IOD_SYMBOL_index1d
#define IOD_SYMBOL_index1d
    iod_define_symbol(index1d)
#endif

#ifndef IOD_SYMBOL_keypoint
#define IOD_SYMBOL_keypoint
    iod_define_symbol(keypoint)
#endif

#ifndef IOD_SYMBOL_keypoint_spacing
#define IOD_SYMBOL_keypoint_spacing
    iod_define_symbol(keypoint_spacing)
#endif

#ifndef IOD_SYMBOL_keypoints
#define IOD_SYMBOL_keypoints
    iod_define_symbol(keypoints)
#endif

#ifndef IOD_SYMBOL_left_to_right
#define IOD_SYMBOL_left_to_right
    iod_define_symbol(left_to_right)
#endif

#ifndef IOD_SYMBOL_lk_iterations
#define IOD_SYMBOL_lk_iterations
    iod_define_symbol(lk_iterations)
#endif

#ifndef IOD_SYMBOL_local_maxima
#define IOD_SYMBOL_local_maxima
    iod_define_symbol(local_maxima)
#endif

#ifndef IOD_SYMBOL_local_search
#define IOD_SYMBOL_local_search
    iod_define_symbol(local_search)
#endif

#ifndef IOD_SYMBOL_mask
#define IOD_SYMBOL_mask
    iod_define_symbol(mask)
#endif

#ifndef IOD_SYMBOL_match
#define IOD_SYMBOL_match
    iod_define_symbol(match)
#endif

#ifndef IOD_SYMBOL_max_points_per_block
#define IOD_SYMBOL_max_points_per_block
    iod_define_symbol(max_points_per_block)
#endif

#ifndef IOD_SYMBOL_max_trajectory_length
#define IOD_SYMBOL_max_trajectory_length
    iod_define_symbol(max_trajectory_length)
#endif

#ifndef IOD_SYMBOL_min_ev
#define IOD_SYMBOL_min_ev
    iod_define_symbol(min_ev)
#endif

#ifndef IOD_SYMBOL_min_scale
#define IOD_SYMBOL_min_scale
    iod_define_symbol(min_scale)
#endif

#ifndef IOD_SYMBOL_niterations
#define IOD_SYMBOL_niterations
    iod_define_symbol(niterations)
#endif

#ifndef IOD_SYMBOL_no_threads
#define IOD_SYMBOL_no_threads
    iod_define_symbol(no_threads)
#endif

#ifndef IOD_SYMBOL_nscales
#define IOD_SYMBOL_nscales
    iod_define_symbol(nscales)
#endif

#ifndef IOD_SYMBOL_patchsize
#define IOD_SYMBOL_patchsize
    iod_define_symbol(patchsize)
#endif

#ifndef IOD_SYMBOL_position
#define IOD_SYMBOL_position
    iod_define_symbol(position)
#endif

#ifndef IOD_SYMBOL_prediction
#define IOD_SYMBOL_prediction
    iod_define_symbol(prediction)
#endif

#ifndef IOD_SYMBOL_propagation
#define IOD_SYMBOL_propagation
    iod_define_symbol(propagation)
#endif

#ifndef IOD_SYMBOL_query
#define IOD_SYMBOL_query
    iod_define_symbol(query)
#endif

#ifndef IOD_SYMBOL_query_positions
#define IOD_SYMBOL_query_positions
    iod_define_symbol(query_positions)
#endif

#ifndef IOD_SYMBOL_radius
#define IOD_SYMBOL_radius
    iod_define_symbol(radius)
#endif

#ifndef IOD_SYMBOL_right_to_left
#define IOD_SYMBOL_right_to_left
    iod_define_symbol(right_to_left)
#endif

#ifndef IOD_SYMBOL_scores
#define IOD_SYMBOL_scores
    iod_define_symbol(scores)
#endif

#ifndef IOD_SYMBOL_search_radius
#define IOD_SYMBOL_search_radius
    iod_define_symbol(search_radius)
#endif

#ifndef IOD_SYMBOL_size1
#define IOD_SYMBOL_size1
    iod_define_symbol(size1)
#endif

#ifndef IOD_SYMBOL_size2
#define IOD_SYMBOL_size2
    iod_define_symbol(size2)
#endif

#ifndef IOD_SYMBOL_subpixelic
#define IOD_SYMBOL_subpixelic
    iod_define_symbol(subpixelic)
#endif

#ifndef IOD_SYMBOL_top_to_bottom
#define IOD_SYMBOL_top_to_bottom
    iod_define_symbol(top_to_bottom)
#endif

#ifndef IOD_SYMBOL_train
#define IOD_SYMBOL_train
    iod_define_symbol(train)
#endif

#ifndef IOD_SYMBOL_train_positions
#define IOD_SYMBOL_train_positions
    iod_define_symbol(train_positions)
#endif

#ifndef IOD_SYMBOL_winsize
#define IOD_SYMBOL_winsize
    iod_define_symbol(winsize)
#endif

