// Generated by iod_generate_symbols.
#include <iod/symbol.hh>
#ifndef IOD_SYMBOL_1
#define IOD_SYMBOL_1
    iod_define_number_symbol(1)
#endif

#ifndef IOD_SYMBOL_approximation
#define IOD_SYMBOL_approximation
    iod_define_symbol(approximation)
#endif

#ifndef IOD_SYMBOL_block_size
#define IOD_SYMBOL_block_size
    iod_define_symbol(block_size)
#endif

#ifndef IOD_SYMBOL_blockwise
#define IOD_SYMBOL_blockwise
    iod_define_symbol(blockwise)
#endif

#ifndef IOD_SYMBOL_blockwise_rank
#define IOD_SYMBOL_blockwise_rank
    iod_define_symbol(blockwise_rank)
#endif

#ifndef IOD_SYMBOL_border
#define IOD_SYMBOL_border
    iod_define_symbol(border)
#endif

#ifndef IOD_SYMBOL_descriptor
#define IOD_SYMBOL_descriptor
    iod_define_symbol(descriptor)
#endif

#ifndef IOD_SYMBOL_detector_period
#define IOD_SYMBOL_detector_period
    iod_define_symbol(detector_period)
#endif

#ifndef IOD_SYMBOL_detector_th
#define IOD_SYMBOL_detector_th
    iod_define_symbol(detector_th)
#endif

#ifndef IOD_SYMBOL_epipolar_flow
#define IOD_SYMBOL_epipolar_flow
    iod_define_symbol(epipolar_flow)
#endif

#ifndef IOD_SYMBOL_epipolar_line_filter
#define IOD_SYMBOL_epipolar_line_filter
    iod_define_symbol(epipolar_line_filter)
#endif

#ifndef IOD_SYMBOL_fundamental_matrix
#define IOD_SYMBOL_fundamental_matrix
    iod_define_symbol(fundamental_matrix)
#endif

#ifndef IOD_SYMBOL_index1d
#define IOD_SYMBOL_index1d
    iod_define_symbol(index1d)
#endif

#ifndef IOD_SYMBOL_keypoint
#define IOD_SYMBOL_keypoint
    iod_define_symbol(keypoint)
#endif

#ifndef IOD_SYMBOL_keypoint_spacing
#define IOD_SYMBOL_keypoint_spacing
    iod_define_symbol(keypoint_spacing)
#endif

#ifndef IOD_SYMBOL_local_maxima
#define IOD_SYMBOL_local_maxima
    iod_define_symbol(local_maxima)
#endif

#ifndef IOD_SYMBOL_mask
#define IOD_SYMBOL_mask
    iod_define_symbol(mask)
#endif

#ifndef IOD_SYMBOL_max_points_per_block
#define IOD_SYMBOL_max_points_per_block
    iod_define_symbol(max_points_per_block)
#endif

#ifndef IOD_SYMBOL_max_trajectory_length
#define IOD_SYMBOL_max_trajectory_length
    iod_define_symbol(max_trajectory_length)
#endif

#ifndef IOD_SYMBOL_min_scale
#define IOD_SYMBOL_min_scale
    iod_define_symbol(min_scale)
#endif

#ifndef IOD_SYMBOL_no_threads
#define IOD_SYMBOL_no_threads
    iod_define_symbol(no_threads)
#endif

#ifndef IOD_SYMBOL_nscales
#define IOD_SYMBOL_nscales
    iod_define_symbol(nscales)
#endif

#ifndef IOD_SYMBOL_patchsize
#define IOD_SYMBOL_patchsize
    iod_define_symbol(patchsize)
#endif

#ifndef IOD_SYMBOL_propagation
#define IOD_SYMBOL_propagation
    iod_define_symbol(propagation)
#endif

#ifndef IOD_SYMBOL_qr_ratio
#define IOD_SYMBOL_qr_ratio
    iod_define_symbol(qr_ratio)
#endif

#ifndef IOD_SYMBOL_regularisation
#define IOD_SYMBOL_regularisation
    iod_define_symbol(regularisation)
#endif

#ifndef IOD_SYMBOL_regularization
#define IOD_SYMBOL_regularization
    iod_define_symbol(regularization)
#endif

#ifndef IOD_SYMBOL_regularization_niters
#define IOD_SYMBOL_regularization_niters
    iod_define_symbol(regularization_niters)
#endif

#ifndef IOD_SYMBOL_scores
#define IOD_SYMBOL_scores
    iod_define_symbol(scores)
#endif

#ifndef IOD_SYMBOL_train
#define IOD_SYMBOL_train
    iod_define_symbol(train)
#endif

#ifndef IOD_SYMBOL_winsize
#define IOD_SYMBOL_winsize
    iod_define_symbol(winsize)
#endif

