// Generated by iod_generate_symbols.
#include <iod/symbol.hh>

#ifndef IOD_SYMBOL_N
#define IOD_SYMBOL_N
    iod_define_symbol(N)
#endif

#ifndef IOD_SYMBOL_aligned
#define IOD_SYMBOL_aligned
    iod_define_symbol(aligned)
#endif

#ifndef IOD_SYMBOL_argmax
#define IOD_SYMBOL_argmax
    iod_define_symbol(argmax)
#endif

#ifndef IOD_SYMBOL_argmin
#define IOD_SYMBOL_argmin
    iod_define_symbol(argmin)
#endif

#ifndef IOD_SYMBOL_avg
#define IOD_SYMBOL_avg
    iod_define_symbol(avg)
#endif

#ifndef IOD_SYMBOL_block_size
#define IOD_SYMBOL_block_size
    iod_define_symbol(block_size)
#endif

#ifndef IOD_SYMBOL_border
#define IOD_SYMBOL_border
    iod_define_symbol(border)
#endif

#ifndef IOD_SYMBOL_col_backward
#define IOD_SYMBOL_col_backward
    iod_define_symbol(col_backward)
#endif

#ifndef IOD_SYMBOL_col_forward
#define IOD_SYMBOL_col_forward
    iod_define_symbol(col_forward)
#endif

#ifndef IOD_SYMBOL_ctx
#define IOD_SYMBOL_ctx
    iod_define_symbol(ctx)
#endif

#ifndef IOD_SYMBOL_data
#define IOD_SYMBOL_data
    iod_define_symbol(data)
#endif

#ifndef IOD_SYMBOL_exp
#define IOD_SYMBOL_exp
    iod_define_symbol(exp)
#endif

#ifndef IOD_SYMBOL_max
#define IOD_SYMBOL_max
    iod_define_symbol(max)
#endif

#ifndef IOD_SYMBOL_mem_backward
#define IOD_SYMBOL_mem_backward
    iod_define_symbol(mem_backward)
#endif

#ifndef IOD_SYMBOL_mem_forward
#define IOD_SYMBOL_mem_forward
    iod_define_symbol(mem_forward)
#endif

#ifndef IOD_SYMBOL_min
#define IOD_SYMBOL_min
    iod_define_symbol(min)
#endif

#ifndef IOD_SYMBOL_n
#define IOD_SYMBOL_n
    iod_define_symbol(n)
#endif

#ifndef IOD_SYMBOL_nbh
#define IOD_SYMBOL_nbh
    iod_define_symbol(nbh)
#endif

#ifndef IOD_SYMBOL_no_threads
#define IOD_SYMBOL_no_threads
    iod_define_symbol(no_threads)
#endif

#ifndef IOD_SYMBOL_options
#define IOD_SYMBOL_options
    iod_define_symbol(options)
#endif

#ifndef IOD_SYMBOL_pitch
#define IOD_SYMBOL_pitch
    iod_define_symbol(pitch)
#endif

#ifndef IOD_SYMBOL_row_backward
#define IOD_SYMBOL_row_backward
    iod_define_symbol(row_backward)
#endif

#ifndef IOD_SYMBOL_row_forward
#define IOD_SYMBOL_row_forward
    iod_define_symbol(row_forward)
#endif

#ifndef IOD_SYMBOL_serial
#define IOD_SYMBOL_serial
    iod_define_symbol(serial)
#endif

#ifndef IOD_SYMBOL_stddev
#define IOD_SYMBOL_stddev
    iod_define_symbol(stddev)
#endif

#ifndef IOD_SYMBOL_sum
#define IOD_SYMBOL_sum
    iod_define_symbol(sum)
#endif

#ifndef IOD_SYMBOL_test
#define IOD_SYMBOL_test
    iod_define_symbol(test)
#endif

#ifndef IOD_SYMBOL_then
#define IOD_SYMBOL_then
    iod_define_symbol(then)
#endif

#ifndef IOD_SYMBOL_tie_arguments
#define IOD_SYMBOL_tie_arguments
    iod_define_symbol(tie_arguments)
#endif

#ifndef IOD_SYMBOL_v
#define IOD_SYMBOL_v
    iod_define_symbol(v)
#endif


#ifndef IOD_SYMBOL_if_
#define IOD_SYMBOL_if_
    iod_define_symbol(if_)
#endif

