// Generated by iod_generate_symbols.
#include <iod/symbol.hh>
#ifndef IOD_SYMBOL_detector_period
#define IOD_SYMBOL_detector_period
    iod_define_symbol(detector_period)
#endif

#ifndef IOD_SYMBOL_detector_th
#define IOD_SYMBOL_detector_th
    iod_define_symbol(detector_th)
#endif

#ifndef IOD_SYMBOL_keypoint_spacing
#define IOD_SYMBOL_keypoint_spacing
    iod_define_symbol(keypoint_spacing)
#endif

