// Generated by iod_generate_symbols.
#include <iod/symbol.hh>
#ifndef IOD_SYMBOL_border
#define IOD_SYMBOL_border
    iod_define_symbol(border)
#endif

#ifndef IOD_SYMBOL_detector_period
#define IOD_SYMBOL_detector_period
    iod_define_symbol(detector_period)
#endif

#ifndef IOD_SYMBOL_detector_th
#define IOD_SYMBOL_detector_th
    iod_define_symbol(detector_th)
#endif

#ifndef IOD_SYMBOL_keypoint_spacing
#define IOD_SYMBOL_keypoint_spacing
    iod_define_symbol(keypoint_spacing)
#endif

#ifndef IOD_SYMBOL_local_maxima
#define IOD_SYMBOL_local_maxima
    iod_define_symbol(local_maxima)
#endif

#ifndef IOD_SYMBOL_no_threads
#define IOD_SYMBOL_no_threads
    iod_define_symbol(no_threads)
#endif

#ifndef IOD_SYMBOL_record_video
#define IOD_SYMBOL_record_video
    iod_define_symbol(record_video)
#endif

#ifndef IOD_SYMBOL_video
#define IOD_SYMBOL_video
    iod_define_symbol(video)
#endif

#ifndef IOD_SYMBOL_type_of_distance
#define IOD_SYMBOL_type_of_distance
    iod_define_symbol(type_of_distance)
#endif

#ifndef IOD_SYMBOL_type_of_kalman_filter
#define IOD_SYMBOL_type_of_kalman_filter
    iod_define_symbol(type_of_kalman_filter)
#endif

#ifndef IOD_SYMBOL_life_time_threshold
#define IOD_SYMBOL_life_time_threshold
    iod_define_symbol(life_time_threshold)
#endif

#ifndef IOD_SYMBOL_distance_threshold
#define IOD_SYMBOL_distance_threshold
    iod_define_symbol(distance_threshold)
#endif

#ifndef IOD_SYMBOL_missed_frame_threshold
#define IOD_SYMBOL_missed_frame_threshold
    iod_define_symbol(missed_frame_threshold)
#endif

#ifndef IOD_SYMBOL_magnitude_acceleration_noise
#define IOD_SYMBOL_magnitude_acceleration_noise
    iod_define_symbol(magnitude_acceleration_noise)
#endif

#ifndef IOD_SYMBOL_life_time_supression_threshold
#define IOD_SYMBOL_life_time_supression_threshold
    iod_define_symbol(life_time_supression_threshold)
#endif

#ifndef IOD_SYMBOL_age_supression_threshold
#define IOD_SYMBOL_age_supression_threshold
    iod_define_symbol(age_supression_threshold)
#endif

#ifndef IOD_SYMBOL_type_hough_video
#define IOD_SYMBOL_type_hough_video
    iod_define_symbol(type_hough_video)
#endif


#ifndef IOD_SYMBOL_type_gradient_video
#define IOD_SYMBOL_type_gradient_video
    iod_define_symbol(type_gradient_video)
#endif

#ifndef IOD_SYMBOL_type_original_video
#define IOD_SYMBOL_type_original_video
    iod_define_symbol(type_original_video)
#endif

#ifndef IOD_SYMBOL_link_of_video_image
#define IOD_SYMBOL_link_of_video_image
    iod_define_symbol(link_of_video_image)
#endif

#ifndef IOD_SYMBOL_gaussian_noise
#define IOD_SYMBOL_gaussian_noise
    iod_define_symbol(gaussian_noise)
#endif

#ifndef IOD_SYMBOL_rayon_exclusion_theta
#define IOD_SYMBOL_rayon_exclusion_theta
    iod_define_symbol(rayon_exclusion_theta)
#endif

#ifndef IOD_SYMBOL_rayon_exclusion_rho
#define IOD_SYMBOL_rayon_exclusion_rho
    iod_define_symbol(rayon_exclusion_rho)
#endif


#ifndef IOD_SYMBOL_slot_hough
#define IOD_SYMBOL_slot_hough
    iod_define_symbol(slot_hough)
#endif

#ifndef IOD_SYMBOL_m_first_lines
#define IOD_SYMBOL_m_first_lines
    iod_define_symbol(m_first_lines)
#endif

#ifndef IOD_SYMBOL_acc_threshold
#define IOD_SYMBOL_acc_threshold
    iod_define_symbol(acc_threshold)
#endif

#ifndef IOD_SYMBOL_nombre_max_frame_without_update
#define IOD_SYMBOL_nombre_max_frame_without_update
    iod_define_symbol(nombre_max_frame_without_update)
#endif




