// Generated by iod_generate_symbols.
#include <iod/symbol.hh>
#ifndef IOD_SYMBOL_border
#define IOD_SYMBOL_border
    iod_define_symbol(border)
#endif

#ifndef IOD_SYMBOL_detector_period
#define IOD_SYMBOL_detector_period
    iod_define_symbol(detector_period)
#endif

#ifndef IOD_SYMBOL_detector_th
#define IOD_SYMBOL_detector_th
    iod_define_symbol(detector_th)
#endif

#ifndef IOD_SYMBOL_keypoint_spacing
#define IOD_SYMBOL_keypoint_spacing
    iod_define_symbol(keypoint_spacing)
#endif

#ifndef IOD_SYMBOL_local_maxima
#define IOD_SYMBOL_local_maxima
    iod_define_symbol(local_maxima)
#endif

#ifndef IOD_SYMBOL_no_threads
#define IOD_SYMBOL_no_threads
    iod_define_symbol(no_threads)
#endif

#ifndef IOD_SYMBOL_record_video
#define IOD_SYMBOL_record_video
    iod_define_symbol(record_video)
#endif

#ifndef IOD_SYMBOL_video
#define IOD_SYMBOL_video
    iod_define_symbol(video)
#endif

