// Generated by iod_generate_symbols.
#include <iod/symbol.hh>
#ifndef IOD_SYMBOL_center
#define IOD_SYMBOL_center
    iod_define_symbol(center)
#endif

#ifndef IOD_SYMBOL_fill
#define IOD_SYMBOL_fill
    iod_define_symbol(fill)
#endif

#ifndef IOD_SYMBOL_stroke
#define IOD_SYMBOL_stroke
    iod_define_symbol(stroke)
#endif

#ifndef IOD_SYMBOL_trajectory_color
#define IOD_SYMBOL_trajectory_color
    iod_define_symbol(trajectory_color)
#endif

#ifndef IOD_SYMBOL_width
#define IOD_SYMBOL_width
    iod_define_symbol(width)
#endif

